#!/usr/bin/env python3
import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "api" / "schema.yaml"
HEADER_PATH = ROOT / "native" / "include" / "generated" / "sogen_dart_generated.h"
DART_PATH = ROOT / "lib" / "src" / "generated" / "types.g.dart"
PUBLIC_HEADER_PATH = ROOT / "native" / "include" / "sogen_dart.h"
FFIGEN_PATH = ROOT / "lib" / "src" / "ffi" / "sogen_native_bindings.g.dart"
MANUAL_FFI_PATHS = (
    ROOT / "lib" / "src" / "ffi" / "linux_runtime_bindings.dart",
    ROOT / "lib" / "src" / "native_library.dart",
)


def snake_case(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def pascal_case(value: str) -> str:
    return value[:1].upper() + value[1:]


def load_schema(path: Path = SCHEMA_PATH) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def validate_schema(schema: dict) -> None:
    if not isinstance(schema.get("abiVersion"), int) or schema["abiVersion"] <= 0:
        raise ValueError("abiVersion must be a positive integer")
    for section in ("statuses", "enums", "dartObjects", "objects", "callbacks"):
        if not isinstance(schema.get(section), dict) or not schema[section]:
            raise ValueError(f"{section} must be a non-empty object")
    for name, layout in schema["dartObjects"].items():
        fields = layout.get("fields", [])
        field_names = [field for _, field in fields]
        if not fields or len(field_names) != len(set(field_names)):
            raise ValueError(f"{name} must have unique Dart accessor fields")
    for name, layout in schema["objects"].items():
        if ("fields" in layout) == ("listOf" in layout):
            raise ValueError(f"{name} must define exactly one of fields or listOf")
        fields = object_fields(layout)
        field_names = [field for _, field in fields]
        if len(field_names) != len(set(field_names)):
            raise ValueError(f"{name} fields must be unique")
    for name, callback in schema["callbacks"].items():
        if not callback.get("return") or not isinstance(callback.get("parameters"), list):
            raise ValueError(f"{name} callback signature is incomplete")
    for platform, slots in schema["callbackSlots"].items():
        ids = [slot["id"] for slot in slots]
        if ids != list(range(len(slots))):
            raise ValueError(f"{platform} callback IDs must be contiguous and ordered")
        names = [slot["name"] for slot in slots]
        fields = [slot["field"] for slot in slots]
        if len(names) != len(set(names)) or len(fields) != len(set(fields)):
            raise ValueError(f"{platform} callback names and fields must be unique")
        for slot in slots:
            if slot["type"] not in schema["callbacks"]:
                raise ValueError(f"Unknown callback type {slot['type']}")


def c_declaration(c_type: str, name: str) -> str:
    return f"  {c_type}{'' if c_type.endswith('*') else ' '}{name};"


def c_parameter(c_type: str, name: str) -> str:
    return f"{c_type}{'' if c_type.endswith('*') else ' '}{name}"


def object_fields(layout: dict) -> list[list[str]]:
    if "fields" in layout:
        return layout["fields"]
    return [[layout["listOf"] + " *", "data"], ["size_t", "length"]]


def generated_header(schema: dict) -> str:
    lines = [
        "#pragma once",
        "",
        "/* Generated by tool/generate_bindings.py. Do not edit. */",
        "",
        f"#define SOGEN_DART_ABI_VERSION {schema['abiVersion']}u",
        "",
        "typedef uint64_t sogen_dart_hook_id;",
        "typedef int32_t sogen_dart_status;",
    ]
    for name, value in schema["statuses"].items():
        lines.append(f"#define SOGEN_DART_{snake_case(name).upper()} {value}")
    lines.append("")

    for name, enum in schema["enums"].items():
        c_name = snake_case(name)
        lines.append(f"typedef int32_t sogen_dart_{c_name};")
        for key, value in enum["values"].items():
            lines.append(
                f"#define SOGEN_DART_{c_name.upper()}_{snake_case(key).upper()} {value}"
            )
        lines.append("")

    for name, layout in schema["objects"].items():
        fields = object_fields(layout)
        c_name = f"sogen_dart_{name}"
        lines.append(f"typedef struct {c_name} {{")
        lines.extend(
            c_declaration(c_type, field)
            for c_type, field in fields
        )
        lines.extend([f"}} {c_name};", ""])

    lines.extend(["// clang-format off", ""])
    for name, callback in schema["callbacks"].items():
        parameters = ", ".join(
            c_parameter(c_type, parameter)
            for c_type, parameter in callback["parameters"]
        )
        lines.extend(
            [
                f"typedef {callback['return']} (*sogen_dart_{name})({parameters});",
                "",
            ]
        )
    lines.extend(["// clang-format on", ""])

    for platform, slots in schema["callbackSlots"].items():
        prefix = f"SOGEN_DART_{platform.upper()}_CALLBACK"
        for slot in slots:
            lines.append(
                f"#define {prefix}_{snake_case(slot['name']).upper()} {slot['id']}"
            )
        lines.extend([f"#define {prefix}_COUNT {len(slots)}", ""])
        c_name = f"sogen_dart_{platform}_callbacks"
        lines.extend([f"typedef struct {c_name} {{", "  void *user_data;"])
        lines.extend(
            f"  sogen_dart_{slot['type']} {slot['field']};" for slot in slots
        )
        lines.extend([f"}} {c_name};", ""])
    return "\n".join(lines)


def generated_dart(schema: dict) -> str:
    lines = ["// Generated by tool/generate_bindings.py. Do not edit.", ""]
    for enum in schema["enums"].values():
        dart_name = enum["dartName"]
        lines.append(f"enum {dart_name} {{")
        values = list(enum["values"].items())
        for index, (name, value) in enumerate(values):
            suffix = ";" if index == len(values) - 1 else ","
            lines.append(f"  {name}({value}){suffix}")
        lines.extend(["", f"  const {dart_name}(this.nativeValue);", "  final int nativeValue;"])
        aliases = enum.get("aliases", {})
        if aliases:
            lines.append("")
            for alias, target in aliases.items():
                lines.append(f"  static const {alias} = {target};")
        lines.extend(["}", ""])
        for alias in enum.get("dartAliases", []):
            lines.extend([f"typedef {alias} = {dart_name};", ""])

    for name, layout in schema["dartObjects"].items():
        fields = layout["fields"]
        lines.extend([f"final class {name} {{", f"  const {name}({{"])
        lines.extend(f"    required this.{field}," for _, field in fields)
        lines.extend(["  });", ""])
        lines.extend(
            f"  final {dart_type} {field};" for dart_type, field in fields
        )
        lines.extend(["}", ""])

    for platform, slots in schema["callbackSlots"].items():
        dart_name = f"{pascal_case(platform)}CallbackSlot"
        lines.append(f"enum {dart_name} {{")
        for index, slot in enumerate(slots):
            aliases = ", ".join(f"'{alias}'" for alias in slot.get("aliases", []))
            suffix = ";" if index == len(slots) - 1 else ","
            compact = (
                f"  {slot['name']}({slot['id']}, '{slot['field']}', "
                f"'{slot['type']}', <String>[{aliases}]){suffix}"
            )
            if len(compact) <= 80:
                lines.append(compact)
            else:
                lines.extend(
                    [
                        f"  {slot['name']}(",
                        f"    {slot['id']},",
                        f"    '{slot['field']}',",
                        f"    '{slot['type']}',",
                        f"    <String>[{aliases}],",
                        f"  ){suffix}",
                    ]
                )
        lines.extend(
            [
                "",
                f"  const {dart_name}(",
                "    this.id,",
                "    this.nativeField,",
                "    this.callbackType,",
                "    this.aliases,",
                "  );",
                "",
                "  final int id;",
                "  final String nativeField;",
                "  final String callbackType;",
                "  final List<String> aliases;",
                "",
                "  bool accepts(String candidate) =>",
                "      name == candidate ||",
                "      nativeField == candidate ||",
                "      aliases.contains(candidate);",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def outputs(schema: dict) -> dict[Path, str]:
    return {HEADER_PATH: generated_header(schema), DART_PATH: generated_dart(schema)}


def _header_function_names(text: str) -> set[str]:
    return set(re.findall(r"\bsogen_dart_(?!status\b)[a-z0-9_]+(?=\s*\()", text))


def _split_parameters(parameters: str) -> list[str]:
    if parameters.strip() in ("", "void"):
        return []
    result = []
    start = 0
    depth = 0
    for index, character in enumerate(parameters):
        if character in "(<":
            depth += 1
        elif character in ")>":
            depth -= 1
        elif character == "," and depth == 0:
            parameter = parameters[start:index].strip()
            if parameter:
                result.append(parameter)
            start = index + 1
    parameter = parameters[start:].strip()
    if parameter:
        result.append(parameter)
    return result


def _header_function_arities(text: str) -> dict[str, int]:
    declarations = re.finditer(
        r"SOGEN_DART_EXPORT\s+.*?\b(sogen_dart_[a-z0-9_]+)\s*"
        r"\((.*?)\)\s*;",
        text,
        re.DOTALL,
    )
    return {
        match.group(1): len(_split_parameters(match.group(2)))
        for match in declarations
    }


def _ffi_function_arity(text: str, name: str) -> int | None:
    helper_arities = {
        "_status": 1,
        "_statusUint64": 2,
        "_statusString": 2,
        "_breakpoint": 3,
    }
    positions = [
        match.start()
        for match in re.finditer(rf"['\"]{re.escape(name)}['\"]", text)
    ]
    for position in positions:
        helper = re.search(
            r"(_statusUint64|_statusString|_status|_breakpoint)\(\s*$",
            text[max(0, position - 80) : position],
        )
        if helper:
            return helper_arities[helper.group(1)]
        prefix = text[max(0, position - 4000) : position]
        functions = list(re.finditer(r"\bFunction\s*\(", prefix))
        if not functions:
            continue
        opening = functions[-1].end() - 1
        depth = 1
        for index in range(opening + 1, len(prefix)):
            if prefix[index] == "(":
                depth += 1
            elif prefix[index] == ")":
                depth -= 1
                if depth == 0:
                    if ";" in prefix[index + 1 :]:
                        break
                    return len(_split_parameters(prefix[opening + 1 : index]))
        helper_call = re.search(r"([a-zA-Z_][a-zA-Z0-9_]*)\(\s*$", prefix)
        if not helper_call:
            continue
        helper = helper_call.group(1)
        for helper_match in re.finditer(rf"\b{re.escape(helper)}\s*\(", text):
            helper_prefix = text[max(0, helper_match.start() - 4000) : helper_match.start()]
            functions = list(re.finditer(r"\bFunction\s*\(", helper_prefix))
            if not functions:
                continue
            opening = functions[-1].end() - 1
            depth = 1
            for index in range(opening + 1, len(helper_prefix)):
                if helper_prefix[index] == "(":
                    depth += 1
                elif helper_prefix[index] == ")":
                    depth -= 1
                    if depth == 0:
                        if ";" in helper_prefix[index + 1 :]:
                            break
                        return len(
                            _split_parameters(helper_prefix[opening + 1 : index])
                        )
    return None


def _header_struct_fields(schema: dict) -> dict[str, set[str]]:
    result = {}
    for name, layout in schema["objects"].items():
        fields = layout.get("fields", [["", "data"], ["", "length"]])
        result[f"sogen_dart_{name}"] = {field for _, field in fields}
    for platform, slots in schema["callbackSlots"].items():
        result[f"sogen_dart_{platform}_callbacks"] = {
            "user_data",
            *(slot["field"] for slot in slots),
        }
    return result


def audit_ffigen(schema: dict) -> list[str]:
    header = PUBLIC_HEADER_PATH.read_text(encoding="utf-8")
    bindings = FFIGEN_PATH.read_text(encoding="utf-8")
    all_bindings = bindings + "\n" + "\n".join(
        path.read_text(encoding="utf-8") for path in MANUAL_FFI_PATHS
    )
    errors = []
    exported_header = header[header.index("SOGEN_DART_EXPORT") :]
    missing_functions = sorted(
        name
        for name in _header_function_names(exported_header)
        if name not in all_bindings
    )
    if missing_functions:
        errors.append("ffigen is missing functions: " + ", ".join(missing_functions))
    for name, expected_arity in _header_function_arities(exported_header).items():
        actual_arity = _ffi_function_arity(all_bindings, name)
        if actual_arity is None:
            errors.append(f"ffigen function signature is not auditable: {name}")
        elif actual_arity != expected_arity:
            errors.append(
                f"ffigen function arity differs from header: {name} "
                f"({actual_arity} != {expected_arity})"
            )
    for struct_name, fields in _header_struct_fields(schema).items():
        match = re.search(
            rf"final class {re.escape(struct_name)} extends ffi\.Struct \{{(.*?)\n\}}",
            bindings,
            re.DOTALL,
        )
        if not match:
            errors.append(f"ffigen is missing struct {struct_name}")
            continue
        body = match.group(1)
        missing = sorted(field for field in fields if not re.search(rf"\b{field}\s*;", body))
        if missing:
            errors.append(f"ffigen {struct_name} is missing fields: {', '.join(missing)}")
    return errors


def audit_public_layouts(schema: dict) -> list[str]:
    header = HEADER_PATH.read_text(encoding="utf-8")
    public_header = PUBLIC_HEADER_PATH.read_text(encoding="utf-8")
    errors = []
    if '#include "generated/sogen_dart_generated.h"' not in public_header:
        errors.append("public header does not include generated declarations")
    for name, layout in schema["objects"].items():
        fields = object_fields(layout)
        c_name = f"sogen_dart_{name}"
        match = re.search(
            rf"typedef struct {re.escape(c_name)} \{{(.*?)\}} {re.escape(c_name)};",
            header,
            re.DOTALL,
        )
        body = "" if not match else re.sub(r"\s+", "", match.group(1))
        expected = "".join(
            re.sub(r"\s+", "", f"{c_type} {field};") for c_type, field in fields
        )
        if body != expected:
            errors.append(f"generated layout differs from schema: {c_name}")
        if re.search(rf"typedef struct {re.escape(c_name)}\s*\{{", public_header):
            errors.append(f"public header duplicates generated layout: {c_name}")
    for name, callback in schema["callbacks"].items():
        if not re.search(rf"\(\*sogen_dart_{re.escape(name)}\)\s*\(", header):
            errors.append(f"public header is missing callback {name}")
    for platform, slots in schema["callbackSlots"].items():
        c_name = f"sogen_dart_{platform}_callbacks"
        match = re.search(
            rf"typedef struct {re.escape(c_name)} \{{(.*?)\}} {re.escape(c_name)};",
            header,
            re.DOTALL,
        )
        fields = [] if not match else re.findall(r"\b([a-z0-9_]+);", match.group(1))
        expected = ["user_data", *(slot["field"] for slot in slots)]
        if fields != expected:
            errors.append(f"generated callback slots differ from schema: {c_name}")
        if re.search(rf"typedef struct {re.escape(c_name)}\s*\{{", public_header):
            errors.append(f"public header duplicates generated callbacks: {c_name}")
    return errors


def check(schema: dict) -> list[str]:
    errors = []
    for path, expected in outputs(schema).items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            errors.append(f"stale generated file: {path.relative_to(ROOT)}")
    errors.extend(audit_public_layouts(schema))
    errors.extend(audit_ffigen(schema))
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files or ffigen declarations are stale")
    args = parser.parse_args(argv)
    schema = load_schema()
    validate_schema(schema)
    if args.check:
        errors = check(schema)
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        return 0
    for path, content in outputs(schema).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
